In [101]:
#Importando librerías
import numpy as np
import matplotlib.pyplot as plt

In [102]:
#Cargando coeficientes
coeff=np.loadtxt('coeff.dat')
print(coeff)

[[ 2.          0.57735027  1.        ]
 [ 2.         -0.57735027  1.        ]
 [ 3.          0.77459667  0.55555556]
 [ 3.          0.          0.88888889]
 [ 3.         -0.77459667  0.55555556]
 [ 4.          0.86113631  0.34785485]
 [ 4.          0.33998104  0.65214515]
 [ 4.         -0.33998104  0.65214515]
 [ 4.         -0.86113631  0.34785485]
 [ 5.          0.90617985  0.23692689]
 [ 5.          0.53846931  0.47862867]
 [ 5.          0.          0.56888889]
 [ 5.         -0.53846931  0.47862867]
 [ 5.         -0.90617985  0.23692689]]


In [111]:
#Función a integrar
def f(x,y):
    #value=np.exp(y/x)
    #value=1.0
    value=4-x**2/9.-y**2/16.
    return value

#Limite inferior y superior de la integral interna
def c(x):
    #value=x**3
    #value=x**2
    value=0
    return value

def d(x):
    #value=x**2
    #value=4*x-x**2
    value=2
    return value

#Limite inferior y superior de la integral externa
a=0
b=3

In [112]:
#Inicia integración
def DoubleGauss(n,m):
    #Creando listas de pesos y raices
    u_i_list=[]
    w_i_list=[]
    t_j_list=[]
    w_j_list=[]
    for i in range(0,coeff.shape[0]):
        if coeff[i][0]==n:
            u_i_list.append(coeff[i][1])
            w_i_list.append(coeff[i][2])            
    for j in range(0,coeff.shape[0]):
        if coeff[j][0]==m:
            t_j_list.append(coeff[j][1])
            w_j_list.append(coeff[j][2])

    sum_i=0
    for i in range(0,n):
        sum_j=0
        x_i=((b-a)*u_i_list[i]+a+b)*0.5
        for j in range(0,m):
            y_j=((d(x_i)-c(x_i))*t_j_list[j]+d(x_i)+c(x_i))*0.5
            sum_j+=w_j_list[j]*f(x_i,y_j)
        sum_i+=w_i_list[i]*(d(x_i)-c(x_i))*sum_j
        
    value=sum_i*(b-a)*0.25
    
    return value
     

In [114]:
print(DoubleGauss(5,5))

21.499999997941543
