In [643]:
#Importando librerías
import numpy as np

In [705]:
#Matriz de coeficientes
#A=[[4,-9,2],[2,-4,6],[1,-1,3]]
#A=[[10,1,-5],[-20,3,20],[5,3,5]]
#A=[[1,1,1],[2,3,-4],[1,-1,1]]
#A=[[1,2,-3],[2,-1,1],[4,-1,1]]
#A=[[80,15,35,60],[28,72,57,25],[20,20,12,20],[50,10,20,60]]
#A=[[2,1,3],[1,0,4],[3,4,3]]
A=[[1,3,12],[0,4,6],[2,5,6]]

A=np.array(A)

#Vector de términos independientes
#B=[5,3,4]
#B=[1,2,6]
#B=[1,9,-1]
#B=[9,0,4]
#B=[230,180,80,160]
#B=[0,1,3]
B=[0.1,3,4]
B=np.array(B)





In [706]:
def row_pivote(A,fil,col):
    max_value=max(A[fil:,col])
    min_value=min(A[fil:,col])
    if(abs(max_value)>abs(min_value)):
        piv=max_value
    else:
        piv=min_value
    for i in range(0,A.shape[0]):
        if A[i][col]==piv:
            row_pivote=i
            break
    
    return row_pivote

In [707]:
def GaussSolver(A,B):
    #Dimensiones de la matriz de coeficientes
    n=A.shape[0]
    m=A.shape[1]
    
    #Creando matriz aumentada
    AB=np.zeros((n,m+1))
    AB[:,0:m]=A
    for i in range(0,len(B)):
        AB[i][m]=B[i]
       
    #Inicia eliminación Gaussiana
    i=0 #Fila inicial
    j=0 #Columna inicial
    
    #Recorriendo columnas
    for h in range(j,m-1): #Notar que no se trabaja sobre última columna de A
        fila_pivote=row_pivote(AB,i,h)  
        pivote=AB[fila_pivote,h]
        if(fila_pivote!=i):
            #Intercambiando filas
            AB[[i,fila_pivote]]=AB[[fila_pivote,i]]
            #Luego de esto, la fila pivote está en la posición i-ésima
        for k in range(i+1,n):
            x=-AB[k][h]/pivote
            AB[k]=AB[k]+AB[i]*x
        i=i+1
        j=j+1
        
    #Inicia sustitución hacia atrás 
    x_sol=np.zeros(n)
    for i in range(n-1,-1,-1):
        if(i==n-1):
            x_sol[i]=AB[i][m]/AB[i][i]
        else:
            sum=0
            for j in range(i+1,m):
                sum+=AB[i][j]*x_sol[j]
            x_sol[i]=(AB[i][m]-sum)/AB[i][i]
                            
    return x_sol




    


In [708]:
print(GaussSolver(A,B))
AA=[[-20,3,20,2],[0,2.5,5,2],[0,3.75,10,6.5]]
AA=np.array(AA)
#print(row_pivote(AA,1))

[-0.08181818  1.16363636 -0.27575758]


In [648]:
R=np.array([[1,2],[3,4]])
print(R)
R[[0,1]]=R[[1,0]]
print(R)

[[1 2]
 [3 4]]
[[3 4]
 [1 2]]


In [652]:
for i in range(3,4):
    print(i)

3
