In [3]:
#importantdo librerías
import numpy as np
import matplotlib.pyplot as plt

In [25]:
#Cargando coeficientes
coeff=np.loadtxt('coeff.dat')
print(coeff)

[[ 2.          0.57735027  1.        ]
 [ 2.         -0.57735027  1.        ]
 [ 3.          0.77459667  0.55555556]
 [ 3.          0.          0.88888889]
 [ 3.         -0.77459667  0.55555556]
 [ 4.          0.86113631  0.34785485]
 [ 4.          0.33998104  0.65214515]
 [ 4.         -0.33998104  0.65214515]
 [ 4.         -0.86113631  0.34785485]
 [ 5.          0.90617985  0.23692689]
 [ 5.          0.53846931  0.47862867]
 [ 5.          0.          0.56888889]
 [ 5.         -0.53846931  0.47862867]
 [ 5.         -0.90617985  0.23692689]]


In [55]:
#Creando función 

def f(x):
    value=(np.sin(x)+np.exp(x)*np.sinh(x))**0.5
    return value

def GaussQuad(a,b,n):
    #Crear las listas de pesos y raices asociadas a un n particular
    w_list=[]
    z_list=[]
    for i in range(0,coeff.shape[0]):
        if int(coeff[i][0])==n:
            z_list.append(coeff[i][1])
            w_list.append(coeff[i][2])
                
    #Aplicamos formula de Cuadratura gaussiana
    f_list=[]
    sum=0.0
    for i in range(0,n):
        argument=((b-a)*z_list[i]+a+b)*0.5
        sum+=w_list[i]*f(argument)
        f_list.append(f(argument))
        
    value=(b-a)*0.5*sum

    return value
    
        

In [58]:
print(GaussQuad(0,1,5))

1.146152252678135
